<a href="https://colab.research.google.com/github/KGrzegorzewski/Project_Euler/blob/main/Project_Euler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [ ]:
sum = 0
for i in range(1000):
  if i%3 == 0 or i%5 == 0:
    sum += i

In [ ]:
print(sum)

233168

#Exercise 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [ ]:
import time

In [ ]:
#Return n-th fibonacci value
def fibonacci(n):
  if n == 0:
    return 0
  if n == 1:
    return 1
  if n == 2:
    return 2
  else:
    return fibonacci(n-1) + fibonacci(n-2)

In [ ]:
#Taki zapis powoduje kilkukrotne liczenie liczb ciagu fibonacciego
start_time = time.process_time()
sum = 0
n = 0
while (fibonacci(n) < 4000000):
  if fibonacci(n) %2 == 0:
    sum += fibonacci(n)
  n += 1

stop_time = time.process_time()
print("Czas potrzebny na policzenie tego zadania: ", round(stop_time - start_time, 3), "s")


#--------------------------------------------------------------------------------------------------

#Taki zapis wymusza jednokrotne policzenie liczby ciagu fibonacciego podczas jednej iteracji
start_time = time.process_time()
sum = 0
n = 0

liczba = fibonacci(n)

while (liczba < 4000000):
  if liczba %2 == 0:
    sum += liczba
  n += 1
  liczba = fibonacci(n)

stop_time = time.process_time()
print("Czas potrzebny na policzenie tego zadania: ", round(stop_time - start_time, 3), "s")

Czas potrzebny na policzenie tego zadania:  5.041 s
Czas potrzebny na policzenie tego zadania:  2.596 s

In [ ]:
print(sum)

4613732

#Exercise 3 (TODO)
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [ ]:
import math

def is_prime(number):
  if number == 0:
    return False
  if number == 1:
    return False

  for i in range(number - 2):
    if number %(i+2) == 0:
      return False
  return True


def prime_factors(number):
  p_factors = []
  i = 2
  while (math.sqrt(number) > 1):
    if is_prime(i):
      if number % i == 0:
        p_factors.append(i)
        number = number / i
      else:
        i += 1

  return p_factors

In [ ]:
prime_factors(1025)

KeyboardInterrupt: ignored

In [ ]:
import math
math.sqrt(3546)

59.54829972383762

#Exercise 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [ ]:
def is_palindrom(number):
  number_str = str(number)
  length_of_string = len(number_str)

  for index in range(length_of_string // 2):
    if number_str[index] != number_str[length_of_string - index - 1]:
      return False
  return True

In [ ]:
is_palindrom(90109)

True

In [ ]:
def max_palindrom_3_dig():
  max = 0
  found_max = []
  start1 = 999
  start2 = 999
  while (start1 > 100):
    while (start2 > 100):
      liczba = start1 * start2
      
      if is_palindrom(liczba):
        if liczba > max:
          max = liczba
          found_max = ([liczba, start1, start2])
      start2 -= 1
    
    start1 -= 1
    start2 = 999
  return found_max

In [ ]:
max_palindrom_3_dig()

[906609, 993, 913]

#Exercise 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [ ]:
list_of_numbers = [i for i in range(1, 21)]

In [ ]:
def is_divided_by_list_of_number(number, list_of_numbers):
  for divider in list_of_numbers:
    if number % divider != 0:
      return False
  return True

In [ ]:
list_of_numbers = [i for i in range(1, 11)]

In [ ]:
#Very bad algorithm... time taken is too long

starting_number = 10
not_found = True
while not_found:
  if is_divided_by_list_of_number(starting_number, list_of_numbers):
    print(starting_number)
    not_found = False
  starting_number += 1

232792560